name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init and Apply
        run: |
          cd terraform/aws
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Python & Ansible
        run: |
          sudo apt update && sudo apt install -y python3-pip
          pip3 install ansible boto3 botocore

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/aws.ini ansible/playbooks/aws_setup.yml